configure: Initialize va_list variable as '{0}' instead of NULL in vsscanf test.
The vsscanf test was generating errors with clang on FreeBSD 8.1 and therefore
our local vsscanf implementation got compiled, leading to MPlayer crashes.
tmp.c:4:26: error: array initializer must be an initializer list


git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32798 b3059339-0415-0410-9bf9-f77b7e298cf2